build:
  dependencies:
    before:
      - 'pecl install mailparse-2.1.6'
  environment:
    postgresql: false
    redis: false
    php:
        version: 5.6
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=cov.xml'
        coverage:
          file: 'cov.xml'
          format: 'clover'
filter:
    paths: ["src/*"]
    excluded_paths:
