build:
  environment:
    postgresql: false
    redis: false
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=cov.xml'
        coverage:
          file: 'cov.xml'
          format: 'clover'
filter:
    paths: ["src/*"]
    excluded_paths:
