language: php

sudo: required

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
    - php: 7.0
      env: COVERAGE=yes
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.1
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.1
  fast_finish: true

before_install:
    - sudo apt-get -y -qq update
#    - sudo apt-get -y -qq install fontconfig libxrender1 xfonts-base xfonts-75dpi

before_script:
    - composer self-update
    - composer install --no-interaction

script:
    - phpunit

cache:
    - bundler
    - apt

notifications:
    email:
        - lr@cwd.at
