language: php

sudo: required

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly
matrix:
    allow_failures:
        - php: hhvm

before_install:
    - sudo apt-get -y -qq update
#    - sudo apt-get -y -qq install fontconfig libxrender1 xfonts-base xfonts-75dpi

before_script:
    - composer self-update
    - composer install --no-interaction

script:
    - phpunit

cache:
    - bundler
    - apt

notifications:
    email:
        - lr@cwd.at
