language: php

sudo: required

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
    - php: 7.0
      env: COVERAGE=yes
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.1
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.1
  fast_finish: true

before_install:
    - sudo apt-get -y -qq update
    - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then composer require --dev --no-update phpunit/phpunit ~5 ; fi

before_script:
    - if [[ "$TRAVIS_PHP_VERSION" = "5.5" ]]; then pecl install mailparse-2.1.6 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then pecl install mailparse-2.1.6 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then pecl install mailparse ; fi
    - composer self-update
    - composer install --no-interaction

script:
    - phpunit

cache:
    - bundler
    - apt

notifications:
    email:
        - lr@cwd.at
